[package]
name = "kosh-network-driver"
version = "0.1.0"
edition = "2021"

[dependencies]
kosh-types = { path = "../../shared/kosh-types" }
kosh-ipc = { path = "../../shared/kosh-ipc" }
spin = { workspace = true }
log = { workspace = true }